site_name:        TaylorSeries.jl
site_description: 'TaylorSeries.jl: A julia package to manipulate Taylor expansions'
repo_url:         https://github.com/JuliaDiff/TaylorSeries.jl
site_author:      Luis Benet

# theme: cinder
theme: bootstrap

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
    - extra
    - mdx_math
    - fenced_code
    - toc:
        permalink: True

docs_dir: 'build'

copyright: "Copyright &copy; 2014-2016, Luis Benet and David P. Sanders.<br>
<a https://github.com/JuliaDiff/TaylorSeries.jl>TaylorSeries.jl</a> is licensed under the
<a href='https://github.com/JuliaDiff/TaylorSeries.jl/blob/master/LICENSE.md'>
MIT Expat license</a>."

pages:
    - 'Home': 'index.md'
    - 'Background': 'background.md'
    - 'User guide':
        - 'User guide': 'user_guide.md'
        - 'Examples': 'examples.md'
    - 'API': 'api.md'
